/* ---------------- QUIZ: ADVANCED ---------------- */
quiz('Advanced',{title:'Advanced recap',goal:'Six questions on consensus, distributed transactions, ids and overload. Answer with a click or keys 1–4.',
  hint:'Count majorities. Prefer undoing steps to locking everything. Shed load before it sheds you.',
  make:quizGame({title:'Advanced',questions:[
    {q:'A five-node Raft cluster loses two nodes. Can it still accept writes?',a:['Yes: three of five is still a majority','No: any lost node stops writes','Only reads, no writes','Only if the leader survived'],why:'Raft needs a majority. With three of five alive, it elects a leader if needed and carries on.',ch:'consensus'},
    {q:'A four-node cluster splits into two halves of two. What happens?',a:['Neither half has a majority, so writes stop','Both halves elect a leader','The half with the old leader carries on','The cluster grows to eight nodes'],why:'Two of four is not a majority. This is why clusters use odd sizes like 3 or 5.',ch:'consensus'},
    {q:'An order spans Payments, Stock and Shipping, each with its own database, and shipping fails. How does a saga recover?',a:['It runs compensating steps: release the stock, refund the payment','It rolls all three databases back at once','It retries forever','It ignores the failure'],why:'Each saga step has an undo. On failure, the steps already done are compensated in reverse order.',ch:'transactions'},
    {q:'What is the main weakness of two-phase commit?',a:['If the coordinator dies mid-commit, participants can be stuck holding locks','It is never consistent','It needs no coordinator','It only works with NoSQL'],why:'Participants that voted yes must wait for the coordinator\'s decision, holding their locks until it returns.',ch:'transactions'},
    {q:'You need ids that are unique across 100 machines, roughly time-ordered and 64 bits long. Which scheme?',a:['Snowflake IDs','Auto-increment from one database','Random UUIDs','Usernames'],why:'Timestamp + machine number + sequence: no coordination, sortable by time, and it fits in 64 bits.',ch:'unique-ids'},
    {q:'A service is overloaded. What is load shedding?',a:['Rejecting some requests early so the rest still succeed','Adding servers automatically','Retrying faster','Caching the errors'],why:'Serving 80% well beats serving 100% so slowly that everything times out.',ch:'backpressure'}]})});
