/* ---------------- QUIZ: ADVANCED ---------------- */
quiz('Advanced',{title:'Advanced recap',goal:'Fourteen questions on consensus, locks, conflicts, distributed transactions, IDs and overload. Answer with a click or keys 1–4.',
  hint:'Count majorities. Prefer undoing steps to locking everything. Shed load before it sheds you.',
  make:quizGame({title:'Advanced',questions:[
    {q:'A five-node Raft cluster loses two nodes. Can it still accept writes?',a:['Yes: three of five is still a majority','No: any lost node stops writes','Only reads, no writes','Only if the leader survived'],why:'Raft needs a majority. With three of five alive, it elects a leader if needed and carries on.',ch:'consensus'},
    {q:'A four-node cluster splits into two halves of two. What happens?',a:['Neither half has a majority, so writes stop','Both halves elect a leader','The half with the old leader carries on','The cluster grows to eight nodes'],why:'Two of four is not a majority. This is why clusters use odd sizes like 3 or 5.',ch:'consensus'},
    {q:'An order spans Payments, Stock and Shipping, and shipping fails. What recovery does a saga attempt?',a:['Compensate completed steps, retry safely and escalate persistent failures','Roll all three databases back at once','Promise automatic recovery in every case','Ignore the failure'],why:'Persist progress and retry idempotent compensation. Recovery can need manual intervention, and irreversible effects cannot simply be undone.',ch:'transactions'},
    {q:'What is the main weakness of two-phase commit?',a:['If the coordinator dies mid-commit, participants can be stuck holding locks','It is never consistent','It needs no coordinator','It only works with NoSQL'],why:'Participants that voted yes must wait for the coordinator\'s decision, holding their locks until it returns.',ch:'transactions'},
    {q:'You need ids across 100 machines, roughly timestamp-ordered and 64 bits long. Which scheme fits with unique machine numbers and guarded clocks?',a:['Snowflake IDs','Auto-increment from one database','UUIDv4','Usernames'],why:'Snowflake packs time, machine and sequence into 64 bits. Clock skew limits cross-server ordering; it does not guarantee causal order.',ch:'unique-ids'},
    {q:'Can an ordinary database sequence guarantee gapless invoice numbers?',a:['No: use a serialized transactional allocator and an audit trail','Yes: every rollback returns its number','Yes: UUIDv4 fixes the gaps','Yes: a Snowflake timestamp is gapless'],why:'Sequence values may be consumed even when a transaction aborts. Business numbering needs explicit allocation and cancellation records.',ch:'unique-ids'},
    {q:'Which UUID version puts a millisecond timestamp first for approximate time ordering?',a:['UUIDv7','UUIDv4','All UUID versions are random','No UUID can contain a timestamp'],why:'UUIDv7 has a timestamp prefix; UUIDv4 is random. Neither establishes global causal order across unsynchronized clocks.',ch:'unique-ids'},
    {q:'A service is overloaded. What is load shedding?',a:['Rejecting some requests early so the rest still succeed','Adding servers automatically','Retrying faster','Caching the errors'],why:'Serving 80% well beats serving 100% so slowly that everything times out.',ch:'backpressure'},
    {q:'A worker pauses, its lock lease expires and another worker takes over. What stops the paused worker\'s stale write?',a:['Storage rejects writes with an older fencing token','A longer timeout on the paused worker','Retrying the write','A bigger server'],why:'The paused worker cannot know it lost the lease. The storage can, by comparing tokens.',ch:'locks'},
    {q:'Version X has clock [A:2, B:0] and version Y has [A:1, B:1]. What are they?',a:['Concurrent: a real conflict','X happened first','Y happened first','The same version'],why:'X is ahead on A and Y is ahead on B, so neither saw the other.',ch:'conflicts'},
    {q:'Can an isolated Raft leader in term 1 believe it leads while another leader exists in term 2?',a:['Yes; higher-term peers reject its stale requests','No; only one node can ever believe it leads','Yes; both can commit without a majority','Yes; terms do not affect requests'],why:'The election guarantee is one elected leader per term. A node steps down when it learns a higher term.',ch:'consensus'},
    {q:'Which Raft entry may a leader commit directly by counting majority replication?',a:['An entry from its current term, under the log-matching rules','Any old-term entry regardless of later log entries','An entry stored only on the leader','Any entry without the voting log restriction'],why:'Current-term majority commitment indirectly commits earlier entries. Candidates must also satisfy the up-to-date-log vote restriction.',ch:'consensus'},
    {q:'X and Y both have vector clock [A:2, B:1]. What is their relationship in this model?',a:['Equal clocks: same version or duplicate','X strictly precedes Y','Y strictly precedes X','Concurrent: each is ahead somewhere'],why:'Causal precedence needs at least one strictly smaller component in addition to componentwise ≤.',ch:'conflicts'},
    {q:'A saga refund keeps failing after safe retries. What should happen?',a:['Retain durable progress, alert and support manual recovery','Declare all effects automatically undone','Forget the failed compensation','Replay the charge without an idempotency key'],why:'Compensation is a business operation that can fail. Persist progress and provide an escalation path for persistent or irreversible effects.',ch:'transactions'}]})});
