/* ---------------- QUIZ: ARCHITECTURE ---------------- */
quiz('Architecture',{title:'Architecture recap',goal:'Six questions on service boundaries, events and observability. Answer with a click or keys 1–4.',
  hint:'Every boundary turns a function call into a network call. Every incident needs data to explain it.',
  make:quizGame({title:'Architecture',questions:[
    {q:'Two features call each other hundreds of times per request. Where should they live?',a:['In the same service','In separate services','In separate data centers','It makes no difference'],why:'Chatty pairs belong together. Split them and every call becomes a slow network hop that can fail.',ch:'microservices'},
    {q:'A small team with one product and no scaling problems is starting out. What is usually the best start?',a:['A well-structured monolith','Forty microservices','One service per database table','A separate function for every endpoint'],why:'Microservices pay off with many teams or very different scaling needs. Early on they mostly add network calls and moving parts.',ch:'microservices'},
    {q:'In an event-driven design, how does Orders tell Email, Stock and Analytics about a new order?',a:['It publishes OrderPlaced and does not need to know who listens','It calls each service in turn','It writes into their databases','It waits for each one to reply'],why:'The publisher stays decoupled. New listeners can be added without touching Orders.',ch:'event-driven'},
    {q:'Checkout is slow for some users. Which signal shows where one request spent its time?',a:['A distributed trace','CPU metrics','A single log line','An uptime check'],why:'A trace follows one request through every service and times each step, so the slow hop stands out.',ch:'observability'},
    {q:'Your alert watches average latency, but users still complain. What should you alert on?',a:['p99 latency, the slowest 1% users actually feel','Average CPU','The number of log lines','Free disk space'],why:'Averages hide the slow tail. A p99 alert fires when a real share of users is suffering.',ch:'observability'},
    {q:'What is the main cost of splitting a monolith into microservices?',a:['In-process calls become network calls that can be slow or fail','The code becomes impossible to test','You can no longer use a database','You must rewrite it in a new language'],why:'You trade simple function calls for timeouts, retries, partial failures and distributed tracing.',ch:'microservices'}]})});
