/* ---------------- QUIZ: CAPSTONE ---------------- */
quiz('Capstone',{title:'Capstone recap',goal:'Seven design questions across the URL shortener, the chat app and the news feed. Answer with a click or keys 1–4.',
  hint:'For each choice, ask: what is read most, what must never be lost, and what happens at the busiest minute?',
  make:quizGame({title:'Capstone',questions:[
    {q:'URL shortener: a link goes viral. What keeps the redirect fast and the database calm?',a:['Cache code → URL in memory','Add an index on the URL column','Make redirects synchronous','Use two-phase commit'],why:'Reads vastly outnumber writes, and one hot code is read again and again: exactly what a cache is for.',ch:'capstone'},
    {q:'URL shortener: counting every click writes to the database on each redirect. What should you do?',a:['Send click events to a queue and count them in the background','Count clicks in the browser','Stop counting clicks','Use a bigger database'],why:'The redirect only needs the URL. Counting can happen just after, through a queue.',ch:'capstone'},
    {q:'Chat app: how does a message reach a friend connected to a different gateway?',a:['The chat service publishes it; the friend\'s gateway is subscribed and pushes it','The sender\'s gateway opens a socket to the friend\'s phone','The friend polls the database every minute','The load balancer forwards it'],why:'Pub/sub decouples gateways: no one needs to know which gateway holds whom.',ch:'capstone-chat'},
    {q:'Chat app: a phone reconnects after a gateway dies. How does it avoid missing or repeating messages?',a:['It asks for everything after the last sequence number it saw','It downloads the whole history again','It waits for the next message','It cannot avoid it'],why:'Per-conversation sequence numbers give an exact resume point, and repeats are easy to ignore.',ch:'capstone-chat'},
    {q:'Chat app: why shard the message store by conversation id?',a:['A conversation\'s history lives together, so loading it is one shard\'s job','It makes every shard the same size forever','It lets messages skip the store','It removes the need for gateways'],why:'Reads load one conversation at a time; keeping it on one shard makes that cheap.',ch:'capstone-chat'},
    {q:'News feed: why not fan out on write for an account with 30 million followers?',a:['One post would mean 30 million writes, backing up the queue for everyone','Followers would see the post twice','It would make reads slower','Celebrities post too rarely to matter'],why:'Treat huge accounts as hot keys: merge their posts at read time instead.',ch:'capstone-feed'},
    {q:'News feed: everyone opens the app at once. What keeps feed loads fast?',a:['Precomputed feeds plus a cache of the first ranked page','Fan-out on read for everyone','More indexes on the posts table','Turning off ranking permanently'],why:'Almost every load is answered from memory, so the spike barely reaches the database.',ch:'capstone-feed'}]})});
