/* ---------------- QUIZ: COMMUNICATION ---------------- */
quiz('Communication',{title:'Communication recap',goal:'Six questions on protocols, queues, pub/sub and async work. Answer with a click or keys 1–4.',
  hint:'Who has to wait for whom? Push or pull? One receiver or many?',
  make:quizGame({title:'Communication',questions:[
    {q:'A chat app must push new messages to users the moment they arrive. What fits best?',a:['WebSockets','REST, polling every minute','gRPC unary calls','A nightly batch job'],why:'A WebSocket stays open, so the server can push a message the instant it exists.',ch:'rest-grpc-ws'},
    {q:'Two internal services exchange thousands of small, typed calls per second. What fits best?',a:['gRPC','REST with JSON','WebSockets','A shared database table'],why:'gRPC\'s compact binary format and typed contracts make internal calls fast and safe.',ch:'rest-grpc-ws'},
    {q:'A new order must update stock, email the customer and notify analytics. With pub/sub, what does the order service publish?',a:['One OrderPlaced event; every subscriber gets a copy','Three messages, one per service','Nothing; the others poll the database','One message per subscriber, sent in turn'],why:'Publishers do not need to know their subscribers. One event fans out to everyone who listens.',ch:'queues-pubsub'},
    {q:'Checkout takes 4 seconds because it also renders a PDF invoice. What do you move off the request path?',a:['The PDF, onto a queue for a background worker','Charging the card','The stock check','Nothing; buy a bigger server'],why:'Do only what the customer must wait for. Everything else can happen just after you reply.',ch:'sync-async'},
    {q:'Consumers fall behind during a sale. What happens to the messages?',a:['They wait in the queue until consumers catch up','They are lost','The producer crashes','They go straight to the database'],why:'Queues absorb bursts. Watch the queue length, though: if it never drains, add consumers.',ch:'queues-pubsub'},
    {q:'Why must a queue consumer cope with getting the same message twice?',a:['Most queues deliver at least once, so handlers must be idempotent','Queues never redeliver, so it cannot happen','It only happens when the queue is broken','The queue drops duplicates itself'],why:'After a crash or timeout a message is redelivered. Processing it twice must be harmless.',ch:'idempotency'}]})});
