/* ---------------- QUIZ: DATA ---------------- */
quiz('Data',{title:'Data recap',goal:'Six questions on indexes, replicas, shards, caches and CAP. Answer with a click or keys 1–4.',
  hint:'Ask what is actually overloaded: reads, writes, one key, or the network between replicas.',
  make:quizGame({title:'Data',questions:[
    {q:'A query looks up one email among 10 million rows and takes seconds. What should you try first?',a:['Add an index on the email column','Put a cache in front','Shard the table','Switch to a NoSQL database'],why:'Without an index the database reads every row. An index finds the row in a handful of page reads.',ch:'indexing'},
    {q:'90% of traffic is reads and the database is overloaded. Which structural fix fits best?',a:['Add followers and send reads to them','Shard by user id','Drop some indexes','Use two-phase commit'],why:'Followers copy the leader and can serve reads. Sharding is for when writes or data size are the problem.',ch:'replication'},
    {q:'You shard users by the first letter of their name. What goes wrong?',a:['Shards fill unevenly, because some letters are far more common','Nothing, it spreads evenly','Joins get faster','You can never add another shard'],why:'A good shard key spreads load evenly, such as a hash of the user id.',ch:'sharding'},
    {q:'A price changes in the database, but users see the old price for up to an hour. What is the likely cause?',a:['A long TTL and no invalidation when the price is written','A missing index','Synchronous replication','A cache that is too small'],why:'The cached copy lives until its TTL runs out. Delete or update it when the price changes.',ch:'cache-invalidation'},
    {q:'A celebrity post gets 50,000 reads a second and its cache key expires. What stops the database being stampeded?',a:['Request coalescing: one fetch, everyone else waits for it','A shorter TTL','More database indexes','Sticky sessions'],why:'Coalescing turns thousands of identical misses into a single database query. Refreshing before expiry helps too.',ch:'hot-keys'},
    {q:'During a network partition, a balance service refuses writes rather than risk two different balances. Which side of CAP did it pick?',a:['Consistency (CP)','Availability (AP)','Both at once','Neither: CAP does not apply'],why:'Refusing to answer rather than risk a wrong answer is the consistent choice. An AP system would answer and reconcile later.',ch:'cap'}]})});
