/* ---------------- QUIZ: FOUNDATIONS ---------------- */
quiz('Foundations',{title:'Foundations recap',goal:'Six questions on page loads, latency, scaling and autoscaling. Answer with a click or keys 1–4.',
  hint:'Latency is one request\'s time; throughput is requests per second. Scaling out survives a crash; autoscaling reacts, it does not predict.',
  make:quizGame({title:'Foundations',questions:[
    {q:'You type example.com and press Enter. What does the browser need before anything else?',a:['The server\'s IP address, from DNS','A TCP connection to example.com','The page\'s HTML','A TLS certificate'],why:'Networks route by number. DNS turns the name into an IP address before any connection can open.',ch:'client-server'},
    {q:'A page takes 300 ms to load and the server finishes 2,000 requests per second. Which number is the latency?',a:['300 ms','2,000 requests per second','Both of them','Neither of them'],why:'Latency is how long one request takes. Throughput is how many requests finish per second.',ch:'scaling'},
    {q:'Your only database server sits at 95% CPU. What is the quickest fix that needs no code changes?',a:['Move it to a bigger machine (scale up)','Add a second identical database (scale out)','Shard the data','Put a CDN in front of it'],why:'Vertical scaling is a hardware change. Scaling a database out needs replication or sharding, which is real design work.',ch:'scaling'},
    {q:'Why do several medium servers usually beat one huge one?',a:['A crash removes only part of the capacity, and they cost less','Each request is always faster','They need no load balancer','They can never run out of memory'],why:'Scaling out spreads the risk: losing one of four servers is a dent, losing your only server is an outage.',ch:'scaling'},
    {q:'An autoscaler adds a server above 70% CPU and removes one below 65%, with no cooldown. What happens?',a:['It flaps, adding and removing servers over and over','It scales perfectly','It never adds a server','It removes every server'],why:'Each change pushes the load across the other threshold. Leave a wide gap between the two and add a cooldown.',ch:'autoscaling'},
    {q:'Traffic doubles in 10 seconds, but a new server takes 2 minutes to boot. What does autoscaling alone give you?',a:['Dropped or slow requests until new servers are ready','Instant extra capacity','Lower latency straight away','Exactly the same as before'],why:'Autoscaling reacts after load rises. Keep headroom, or scale ahead of spikes you can predict.',ch:'autoscaling'}]})});
