/* ---------------- QUIZ: RELIABILITY ---------------- */
quiz('Reliability',{title:'Reliability recap',goal:'Six questions on single points of failure, timeouts, retries and idempotency. Answer with a click or keys 1–4.',
  hint:'Failures will happen. The question is whether they spread, and whether retrying is safe.',
  make:quizGame({title:'Reliability',questions:[
    {q:'Which of these is a single point of failure?',a:['One database with no replica, behind two app servers','Two app servers behind a load balancer','A managed, multi-region DNS service','A three-node Raft cluster'],why:'If that one database dies, everything stops, however many app servers sit in front of it.',ch:'spof'},
    {q:'Web waits 2 s for Orders; Orders waits 5 s for Payments. Payments hangs. What goes wrong?',a:['Orders keeps working for 3 s after Web has given up','Nothing goes wrong','Web waits the full 5 s','Payments times out first'],why:'Inner timeouts must be shorter than outer ones, or work carries on for a caller who has left. Pass a deadline down.',ch:'timeouts'},
    {q:'A thousand clients all retry a failed call after exactly one second. What should you add?',a:['Exponential backoff with jitter','More retries','A shorter timeout','Sticky sessions'],why:'Backoff spaces the retries out, and jitter stops every client retrying at the same instant.',ch:'resilience'},
    {q:'A dependency is down. What does a circuit breaker do?',a:['Fails calls fast for a while, then probes to see if it has recovered','Retries forever','Restarts the dependency','Caches the error responses'],why:'Failing fast frees your threads and gives the dependency room to recover.',ch:'resilience'},
    {q:'A payment request times out and the client retries. How do you avoid charging twice?',a:['Send an idempotency key; a repeat gets the saved result','Never retry payments','Use a longer timeout','Retry with a different card'],why:'The server remembers each key\'s result, so a retry returns the first answer instead of charging again.',ch:'idempotency'},
    {q:'Which operation is naturally idempotent?',a:['Set the email address to sam@example.com','Add $10 to the balance','Append a comment','Send a welcome email'],why:'Setting a value twice leaves the same result. Adding, appending and sending all repeat their effect.',ch:'idempotency'}]})});
