/* ---------------- QUIZ: STORAGE & SEARCH ---------------- */
quiz('Storage & Search',{title:'Storage & Search recap',goal:'Six questions on storage engines, search indexes and location queries. Answer with a click or keys 1–4.',
  hint:'Ask how the data is laid out: sorted pages, sorted files merged later, term → documents, or cells on a map.',
  make:quizGame({title:'Storage & Search',questions:[
    {q:'Why do LSM trees handle heavy write loads well?',a:['Writes go to memory and are flushed to disk as large sequential files','They never write to disk','Every write updates a single page in place','They skip the write-ahead log'],why:'Turning many small random writes into a few big sequential ones is what makes LSM writes cheap.',ch:'storage-engines'},
    {q:'What is the price an LSM tree pays for its fast writes?',a:['Reads may check several files, and compaction uses disk in the background','It cannot store sorted data','It loses data on a crash','It only supports one writer per day'],why:'Bloom filters and compaction keep reads fast, but both cost memory, disk and CPU.',ch:'storage-engines'},
    {q:'What does an inverted index map?',a:['Each term to the list of documents that contain it','Each document to its file size','Each user to their last search','Each row to its primary key'],why:'Term → postings list is what lets search skip documents that cannot match.',ch:'search'},
    {q:'How does a search engine answer "redis AND cache"?',a:['Intersect the postings lists for the two terms','Read every document and look for both words','Add the two lists together','Sort the documents by date'],why:'AND keeps only documents in both lists. OR would take the union.',ch:'search'},
    {q:'Why does a geohash lookup check the eight neighbouring cells as well?',a:['The nearest point may sit just across a cell edge','Neighbours always have more drivers','It makes the codes shorter','Cells overlap each other'],why:'Cells are squares, not circles around the rider, so the true nearest point can be next door.',ch:'geo'},
    {q:'Downtown has thousands of drivers, the suburbs very few. What does a quadtree do?',a:['Splits busy areas into smaller cells and leaves quiet ones large','Gives every area the same cell size','Stores drivers in one big list','Deletes drivers in quiet areas'],why:'Splitting only where points are dense keeps every cell small enough to search quickly.',ch:'geo'}]})});
