/* ---------------- QUIZ: TRAFFIC ---------------- */
quiz('Traffic',{title:'Traffic recap',goal:'Seven questions on load balancing, sessions, gateways, CDNs and rate limits. Answer with a click or keys 1–4.',
  hint:'Think about where each decision is best made: at the balancer, at the gateway, at the edge, or in a shared store.',
  make:quizGame({title:'Traffic',questions:[
    {q:'One server is older and slower, and requests vary a lot in size. Which balancing strategy fits best?',a:['Least connections','Round robin','Random','Always the first server'],why:'Least connections looks at how busy each server really is, so the slow one naturally gets less work.',ch:'load-balancers'},
    {q:'Users get logged out whenever the load balancer moves them to another server. What is the most robust fix?',a:['Keep sessions in a shared store such as Redis','Turn on sticky sessions','Add more servers','Make sessions last longer'],why:'Sticky sessions help only until a server dies. With a shared store, any server can serve any user.',ch:'sessions'},
    {q:'Twenty internal services all need token checks and rate limits. Where should that happen?',a:['Once, at the API gateway','Separately inside every service','In the database','In the user\'s browser'],why:'The gateway is the single front door, so cross-cutting checks happen once, before any service sees the request.',ch:'proxy-gateway'},
    {q:'A video is requested by users on four continents. What cuts their wait the most?',a:['Serving it from CDN edge caches near them','A bigger origin server','A faster database','Switching from REST to gRPC'],why:'Distance is latency. Edge caches serve the bytes from close by, so most requests never cross an ocean.',ch:'cdn'},
    {q:'You want to allow short bursts but cap the average at 10 requests per second. Which limiter fits?',a:['Token bucket','Leaky bucket','No limiter, just add servers','A longer timeout'],why:'A token bucket saves unused tokens for bursts, while its refill rate caps the average. A leaky bucket smooths everything to one fixed rate.',ch:'rate-limiting'},
    {q:'A client goes over its rate limit. What should the server send back?',a:['429 Too Many Requests','500 Internal Server Error','200 OK with an empty body','301 Moved Permanently'],why:'429 tells the client it is being limited, ideally with a Retry-After header, so it can back off.',ch:'rate-limiting'},
    {q:'Logging out must take effect immediately in your one web app. Which credential fits best?',a:['A session cookie backed by a session store','A JWT that lasts 30 days','An API key in the URL','No credential at all'],why:'Deleting the session revokes it at once. A JWT stays valid until it expires.',ch:'auth'}]})});
