/* ============================================================
   GLOSSARY: [term, definition, other spellings that should match]
   The first few terms in each caption, transcript line and trade-off
   become focusable; hover, focus or tap shows the definition.
   All-caps spellings (CAP, TTL, DNS…) match case-sensitively.
   ============================================================ */
const GLOSSARY=[
['packet','A small chunk of data sent over a network, labelled with where it came from and where it is going.',['packets']],
['IP address','The numeric address of a machine on a network, like 93.184.216.34.',['IP addresses']],
['port','A number that picks which program on a machine gets the traffic, like 443 for HTTPS.',['ports']],
['router','A device that passes packets one hop closer to their destination.',['routers']],
['DNS','The internet\'s phone book: it turns a name like example.com into an IP address.',[]],
['TCP','The protocol that turns lossy packets into a reliable, ordered stream, resending anything lost.',[]],
['TLS','Encryption for a connection; the S in HTTPS.',['HTTPS']],
['latency','How long one request takes, start to finish.',[]],
['throughput','How many requests a system finishes per second.',[]],
['p99','The 99th-percentile latency: 99% of requests are faster than this, 1% slower.',['p99 latency']],
['vertical scaling','Making one machine bigger: more CPU, more memory.',['scale up','scaling up']],
['horizontal scaling','Adding more machines and spreading the work across them.',['scale out','scaling out']],
['autoscaling','Adding and removing servers automatically as load rises and falls.',['autoscaler']],
['cooldown','A pause after a scaling action so the system settles before the next one.',[]],
['load balancer','A component that spreads incoming requests across several servers.',['load balancers','load balancing']],
['round robin','Sending requests to servers in turn: 1, 2, 3, 1, 2, 3…',[]],
['least connections','Sending each request to the server with the fewest requests in progress.',[]],
['health check','A small, regular request that tells a load balancer whether a server is alive.',['health checks']],
['stateless','Keeping nothing about users between requests, so any server can handle any request.',[]],
['sticky session','Pinning a user to one server so their in-memory session stays reachable.',['sticky sessions']],
['session','What a server remembers about a logged-in user between requests.',['sessions']],
['reverse proxy','A server in front of your servers that receives requests and forwards them.',['reverse proxies']],
['API gateway','The single front door for an API: routing, authentication and rate limits in one place.',['gateway']],
['CDN','A network of caches around the world that serve content from close to the user.',['CDNs']],
['edge server','A CDN server close to users that keeps copies of content, so requests need not travel to the origin.',['edge servers','edge','edges','edge cache','edge caches']],
['origin','The main server that holds the real content; caches fetch from it.',['origin server']],
['rate limiting','Capping how many requests a client may make in a period.',['rate limit','rate limits','rate limiter']],
['token bucket','A rate limiter that refills tokens at a steady rate; each request spends one, and bursts can use saved tokens.',[]],
['leaky bucket','A rate limiter that queues requests and lets them out at a fixed rate.',[]],
['429','The HTTP status Too Many Requests, sent when a rate limit rejects a request.',[]],
['SQL','Relational databases: tables with a fixed schema, joins and transactions.',[]],
['NoSQL','Non-relational databases (document, key-value, wide-column) that trade joins for flexible schemas and easy scaling.',[]],
['schema','The declared shape of the data: tables, columns and their types.',[]],
['index','A sorted lookup structure that lets a database find rows without reading them all.',['indexes','indexing']],
['B-tree','The balanced tree most databases use for indexes; a few page reads reach any row.',[]],
['full table scan','Reading every row to find matches, because no index helps.',['full scan']],
['replication','Keeping copies of the same data on several machines.',['replica','replicas']],
['leader','The replica that accepts writes and passes them on to the others.',[]],
['follower','A replica that copies the leader\'s writes and can serve reads.',['followers','read replica','read replicas']],
['replication lag','How far behind the leader a follower is.',['lag']],
['sharding','Splitting data across machines so each holds only part of it.',['shard','shards','partitioning']],
['shard key','The field that decides which shard a row lives on.',[]],
['consistent hashing','Placing keys and servers on a ring, so adding a server moves only a small share of keys.',[]],
['cache','A fast store, usually in memory, that keeps copies of data that is slow to fetch.',['caches','caching']],
['cache hit','The data was already in the cache.',['hit rate']],
['cache miss','The data was not in the cache and had to be fetched from the slower store.',[]],
['LRU','Least Recently Used: when the cache is full, evict the item unused for longest.',[]],
['eviction','Removing an item from a full cache to make room.',['evict']],
['TTL','Time to live: how long a cached copy may be used before it expires.',[]],
['cache invalidation','Removing or updating cached copies when the real data changes.',['invalidation','invalidate']],
['cache-aside','The app checks the cache first and, on a miss, reads the database and fills the cache.',[]],
['write-through','Writes update the cache and the database together before replying.',[]],
['write-back','Writes go to the cache now and reach the database later.',[]],
['hot key','A single key that receives a large share of all traffic.',['hot keys']],
['request coalescing','Merging identical in-flight requests so only one reaches the database.',['coalescing','coalesce']],
['cache stampede','Many requests miss the same expired key at once and all hit the database.',['stampede','thundering herd']],
['CAP theorem','During a network partition, a distributed store must choose between consistency and availability.',['CAP']],
['network partition','A network split that stops some nodes from reaching others.',['partition']],
['strong consistency','Every read sees the latest write.',[]],
['eventual consistency','Replicas may disagree for a while, but agree once writes stop.',['eventually consistent']],
['REST','HTTP APIs built around resources and verbs (GET, POST), usually with JSON.',[]],
['gRPC','Fast binary calls over HTTP/2 with typed contracts; common between internal services.',[]],
['WebSocket','A connection that stays open so client and server can both send messages at any time.',['WebSockets']],
['message queue','A buffer between services: producers add messages, consumers take them off at their own pace.',['queue','queues']],
['pub/sub','Publish/subscribe: one message is delivered to every subscriber of a topic.',['publish/subscribe']],
['producer','A service that puts messages on a queue.',['producers','publisher']],
['consumer','A service that takes messages off a queue and processes them.',['consumers','subscriber','subscribers']],
['asynchronous','The caller does not wait: work is handed off and finished later.',['async']],
['single point of failure','A component whose failure takes the whole system down.',['SPOF','single points of failure']],
['redundancy','Extra copies of a component so one failure is not fatal.',['redundant']],
['failover','Switching to a standby when the active component fails.',['standby']],
['timeout','How long a caller waits before giving up.',['timeouts']],
['deadline','The total time budget for a request, passed along so each hop knows how long is left.',['deadlines']],
['retry','Trying a failed request again.',['retries']],
['exponential backoff','Waiting longer before each retry: 1 s, 2 s, 4 s…',['backoff']],
['jitter','Random variation in retry delays, so clients do not all retry at the same moment.',[]],
['circuit breaker','Stops calling a failing service for a while, failing fast so it can recover.',['circuit breakers']],
['idempotent','Safe to repeat: doing it twice has the same effect as doing it once.',['idempotency']],
['idempotency key','A unique id sent with a request so the server can spot and ignore duplicates.',[]],
['monolith','One application that holds every feature and deploys as one unit.',[]],
['microservices','Many small services, each owning one job and its data, talking over the network.',['microservice']],
['event-driven','Services announce what happened as events; others react without the sender knowing who listens.',[]],
['observability','Being able to tell what a system is doing from the outside, using logs, metrics and traces.',[]],
['metrics','Numbers measured over time, like requests per second or p99 latency.',[]],
['logs','Timestamped records of individual events.',[]],
['trace','The path of one request through every service, with a timing for each step.',['traces','distributed trace']],
['span','One timed step inside a trace.',['spans']],
['consensus','Getting several machines to agree on one value, even when some fail.',[]],
['Raft','A consensus algorithm: nodes elect a leader, which copies a log to a majority.',[]],
['majority','More than half of the nodes: enough agreement to make progress safely.',['quorum']],
['heartbeat','A regular "I\'m alive" message; when they stop, others react.',['heartbeats']],
['leader election','Choosing a new leader when the old one stops sending heartbeats.',['election']],
['two-phase commit','A coordinator asks every participant to prepare, then tells all of them to commit or all to abort.',['2PC']],
['saga','A long transaction split into steps, each with a compensating step that undoes it.',['sagas']],
['compensation','An action that undoes an earlier step, like a refund for a charge.',['compensating']],
['Snowflake ID','A 64-bit id made of a timestamp, a machine number and a sequence, so machines can create ids without coordinating.',['Snowflake','Snowflake IDs']],
['UUID','A random 128-bit id: practically never collides, but large and unordered.',['UUIDs']],
['back-pressure','A slow component signalling upstream to slow down instead of being overwhelmed.',['backpressure']],
['load shedding','Deliberately rejecting some requests under overload so the rest still succeed.',[]],
['base62','Writing numbers with 0–9, a–z and A–Z, which makes short codes.',[]],
['301','A permanent HTTP redirect; browsers remember it.',[]],
['302','A temporary HTTP redirect; browsers ask again every time.',[]]];
